name: Deploy Editor

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  should-run-app:
    uses: ./.github/workflows/workflow__check_for_changes.yml
    with:
      workflow-name: "Deploy Editor"
      app-name: editor-app

  build-app:
    runs-on: 'ubuntu-latest'
    needs: should-run-app
    if: needs.should-run-app.outputs.should-run

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: https://mioto.azurecr.io/
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: mioto.azurecr.io/mioto/mioto-editor:${{ github.sha }}
        file: ./apps/editor/Dockerfile
        secrets: |
          "DOTENV_PRIVATE_KEY_PRODUCTION=${{ secrets.DOTENV_PRIVATE_KEY_PRODUCTION }}"

  deploy-app:
    needs: ['build-sync-server', 'build-app']
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EDITOR_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EDITOR_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EDITOR_AZURE_SUBSCRIPTION_ID }}
      - name: Deploy image
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: mioto.azurecr.io/mioto/mioto-editor:${{ github.sha }}
          containerAppName: editor
          resourceGroup: mioto-editor

  should-run-sync-server:
    uses: ./.github/workflows/workflow__check_for_changes.yml
    with:
      workflow-name: "Deploy Editor"
      app-name: editor-sync-server

  build-sync-server:
    runs-on: 'ubuntu-latest'
    needs: should-run-sync-server
    if: needs.should-run-sync-server.outputs.should-run

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: https://mioto.azurecr.io/
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: mioto.azurecr.io/mioto/sync-server:${{ github.sha }}
        file: ./apps/sync-server/Dockerfile

  deploy:
    needs: ['build-sync-server', 'build-app']
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EDITOR_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EDITOR_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EDITOR_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy image
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: mioto.azurecr.io/mioto/sync-server:${{ github.sha }}
          containerAppName: editor-sync-server
          resourceGroup: mioto-editor