# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: mind-app

on:
  # push:
  #   branches:
  #     - mioto-mind
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      shouldSkip: ${{ steps.check-change.outputs.shouldSkip }}

    steps:
      - run: |
          result="$(gh run list -w editor-app -R https://github.com/miotolabs/mioto --json conclusion,headSha -L 50 --jq '.[] | select(.conclusion=="success") | .headSha' | head -1)"

          echo 'LAST_SUCCESSFULL_COMMIT_SHA='$result >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - id: check-change
        shell: bash
        continue-on-error: true
        # The output here is only set if the docker:ignore does not fail. That means that the
        # output is only set if the apps files have NOT changed.
        run: |
          pnpm run -r -F mind-functions ignore --fallback=$LAST_SUCCESSFULL_COMMIT_SHA && \
          echo "shouldSkip=$?" >> "$GITHUB_OUTPUT"

      - name: Summary
        shell: bash
        # The run is skipped if the apps files have not changed.
        if: ${{ steps.check-change.outputs.shouldSkip }}
        run: |
          echo "The run is skipped, because no change happened in the apps files." >> $GITHUB_STEP_SUMMARY

      - name: Cancel the current workflow run
        # The run is skipped if the apps files have not changed.
        if: ${{ steps.check-change.outputs.shouldSkip }}
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run cancel $GITHUB_RUN_ID -R https://github.com/$OWNER/$REPO

  build:
    runs-on: 'ubuntu-latest'
    needs: check
    if: ${{ needs.check.outputs.shouldSkip == '0' }}

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: https://mioto.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8fb58dc36f9e481bad2d50cb6ec656b5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_86edc4af97284c848ed071a3e5ffc4bf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: mioto.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8fb58dc36f9e481bad2d50cb6ec656b5 }}/mioto-mind:${{ github.sha }}
        file: ./apps/mioto-mind/app/Dockerfile
        secrets: |
          "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
          "AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}"
          "TIPTAP_TOKEN=${{ secrets.TIPTAP_TOKEN }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'mind-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e577881f30864a6db1c5c8cca0fa6308 }}
        images: 'mioto.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8fb58dc36f9e481bad2d50cb6ec656b5 }}/mioto-mind:${{ github.sha }}'